### ISSUE TITLE
From Woofer:

### ISSUE THREAD

**Issue by eleegha** [RetroPronghorn/Vault74#1]
Browser 1: Google Chrome 87.0.4280.66 (Official Build) (64-bit)
Browser 2: Firefox Version 03.0 (64-bit)
OS: Windows 10 home, Version: 2004, OS build: 19041.630
-------------------------------------------------------------------------
Bug: X user is typing message stays on screen 
-------------------------------------------------------------------------
How to repro: Account 1 types out a message, on account 2 wait until the 'x user is typing" message disappears, then tell account 1 to send the message (if its your account send it), it will then show x user is typing even though x user is not typing and it wont disappear. (see attached for video explanation)
-------------------------------------------------------------------------

**Comment by eleegha** [comment]
https://media.discordapp.net/attachments/780868186366279711/780881890533965864/Hnet-image.gif?width=540&height=302

**Comment by Woofer21** [comment]
I belive this bug was fixed

**Comment by eleegha** [comment]
> I belive this bug was fixed

okay!

**Comment by RetroPronghorn** [comment]
while this hasn't yet been resolved, I am not willing to hack the fix for this just yet. Going to leave this open for the future.

**Comment by Suryaansh2112** [comment]
@RetroPronghorn I can vouch and approve that the bug is fixed The new version I was attempting calls with multiple people for a different bug and it seems the typing bug is fixed

**Comment by RetroPronghorn** [comment]
@Suryaansh2112 thank you, closing issue
