### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Woofer21** [RetroPronghorn/Vault74#2]
Browser: Google Chrome
OS: Windows 10 Pro, Version: 20H2, OS build: 19042.630
-------------------------------------------------------------------------
Bug: Auto scrolls to the first message in history instead of the last message
-------------------------------------------------------------------------
How to repro: if you click into a chat for someone and then go into a chat with someone else whose message history goes beyond the main page, I auto scrolls to the first message sent instead of the last message sent
-------------------------------------------------------------------------
Users who can repro:
Me: Google Chrome Version 87.0.4280.66 (Official Build) (64-bit), Windows 10 home, Version: 2004, OS build: 19041.630
eleegha : Google Chrome OS Version 86.0.4240.198 (Official Build) (64-bit), OS is the same

**Comment by RetroPronghorn** [comment]
Resolved (mostly) in the new version coming soon. In the future i'd like to use a better library for scrolling
