### ISSUE TITLE
Bug with changing Profile Pictures (Latest release) 

### ISSUE THREAD

**Issue by Imacreeper2013** [RetroPronghorn/Vault74#6]
Operating System: Windows 10 OS Version 1909 (18363.1198)
Browser version: Google Chrome 86.0.4240.198 (Official Build) (64-bit)
Vault74 version: Latest (QmQFg9aW8d9wv68izCb4BoePcarkmAwJp6uQ8z5CaAXktR/) 
Bug: Changing Profile Pictures requires you to pay 0.005781 test ETH
How to reproduce: settings -> profile -> change photo -> upload new image, then click save.
Extra Information:

![Capture](https://user-images.githubusercontent.com/71351906/100934887-3bf31780-34a4-11eb-99d5-17633a7054dd.PNG)

**Comment by RetroPronghorn** [comment]
This is intended. This is the gas price of writing to the Ethereum blockchain. It will remain until abstractions are implemented in beta.
